# Generated by Django 4.2.7 on 2023-12-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='j', upload_to='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='k', upload_to='news'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='short_text',
            field=models.CharField(default='tesrt', max_length=250),
            preserve_default=False,
        ),
    ]
